export const BID_CREATE_REQUEST = 'BID_CREATE_REQUEST'
export const BID_CREATE_SUCCESS = 'BID_CREATE_SUCCESS'
export const BID_CREATE_FAIL = 'BID_CREATE_FAIL'


export const BID_DETAILS_REQUEST = 'BID_DETAILS_REQUEST'
export const BID_DETAILS_SUCCESS = 'BID_DETAILS_SUCCESS'
export const BID_DETAILS_FAIL = 'BID_DETAILS_FAIL'
export const BID_DETAILS_RESET = 'BID_DETAILS_RESET'


export const BID_DETAILS_USER_REQUEST = 'BID_DETAILS_USER_REQUEST'
export const BID_DETAILS_USER_SUCCESS = 'BID_DETAILS_USER_SUCCESS'
export const BID_DETAILS_USER_FAIL = 'BID_DETAILS_USER_FAIL'
export const BID_DETAILS_USER_RESET = 'BID_DETAILS_USER_RESET'


export const BID_DELETE_REQUEST = 'BID_DELETE_REQUEST'
export const BID_DELETE_SUCCESS = 'BID_DELETE_SUCCESS '
export const BID_DELETE_FAIL = 'BID_DELETE_FAIL'


export const BIDS_LIST_REQUEST = 'BIDS_LIST_REQUEST'
export const BIDS_LIST_SUCCESS = 'BIDS_LIST_SUCCESS'
export const BIDS_LIST_FAIL = 'BIDS_LIST_FAIL'
export const BIDS_LIST_RESET = 'BIDS_LIST_RESET'

export const WRITER_BIDS_LIST_REQUEST = 'WRITER_BIDS_LIST_REQUEST'
export const WRITER_BIDS_LIST_SUCCESS = 'WRITER_BIDS_LIST_SUCCESS'
export const WRITER_BIDS_LIST_FAIL = 'WRITER_BIDS_LIST_FAIL'
export const WRITER_BIDS_LIST_RESET = 'WRITER_BIDS_LIST_RESET'