export const CREATE_FINE_REQUEST = 'CREATE_FINE_REQUEST'
export const CREATE_FINE_SUCCESS = 'CREATE_FINE_SUCCESS'
export const CREATE_FINE_FAIL = 'CREATE_FINE_FAIL'
export const CREATE_FINE_RESET = 'CREATE_FINE_RESET'


export const LIST_FINES_REQUEST = 'LIST_FINES_REQUEST'
export const LIST_FINES_SUCCESS = 'LIST_FINES_SUCCESS'
export const LIST_FINES_FAIL = 'LIST_FINES_FAIL'
export const LIST_FINES_RESET = 'LIST_FINES_RESET'


export const FINE_DETAILS_REQUEST = 'FINE_DETAILS_REQUEST'
export const FINE_DETAILS_SUCCESS = 'FINE_DETAILS_SUCCESS'
export const FINE_DETAILS_FAIL = 'FINE_DETAILS_FAIL'
export const FINE_DETAILS_RESET = 'FINE_DETAILS_RESET'



export const FINE_UPDATE_REQUEST = 'FINE_UPDATE_REQUEST'
export const FINE_UPDATE_SUCCESS = 'FINE_UPDATE_SUCCESS'
export const FINE_UPDATE_FAIL = 'FINE_UPDATE_FAIL'
export const FINE_UPDATE_RESET = 'FINE_UPDATE_RESET'


export const FINE_DELETE_REQUEST = 'FINE_DELETE_REQUEST'
export const FINE_DELETE_SUCCESS = 'FINE_DELETE_SUCCESS '
export const FINE_DELETE_FAIL = 'FINE_DELETE_FAIL'
export const FINE_DELETE_RESET = 'FINE_DELETE_RESET'


export const FINES_BY_USER_REQUEST = 'FINES_BY_USER_REQUEST'
export const FINES_BY_USER_SUCCESS = 'FINES_BY_USER_SUCCESS'
export const FINES_BY_USER_FAIL = 'FINES_BY_USER_FAIL'
export const FINES_BY_USER_RESET = 'FINES_BY_USER_RESET'