export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ASSIGN_WRITER_REQUEST = 'ASSIGN_WRITER_REQUEST'
export const ASSIGN_WRITER_SUCCESS = 'ASSIGN_WRITER_SUCCESS'
export const ASSIGN_WRITER_FAIL = 'ASSIGN_WRITER_FAIL'

export const ASSIGNED_ORDER_LIST_REQUEST= 'ASSIGNED_ORDER_LIST_REQUEST'
export const ASSIGNED_ORDER_LIST_SUCCESS= 'ASSIGNED_ORDER_LIST_SUCCESS'
export const ASSIGNED_ORDER_LIST_FAIL= 'ASSIGNED_ORDER_LIST_FAIL'
export const ASSIGNED_ORDER_LIST_RESET= 'ASSIGNED_ORDER_LIST_RESET'

export const DOWNLOAD_ATTACHMENT_REQUEST= 'DOWNLOAD_ATTACHMENT_REQUEST'
export const DOWNLOAD_ATTACHMENT_SUCCESS= 'DOWNLOAD_ATTACHMENT_SUCCESS'
export const DOWNLOAD_ATTACHMENT_FAIL= 'DOWNLOAD_ATTACHMENT_FAIL'
export const DOWNLOAD_ATTACHMENT_RESET= 'DOWNLOAD_ATTACHMENT_RESET'



export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST'
export const LIST_ORDERS_SUCCESS = 'LIST_ORDERS_SUCCESS'
export const LIST_ORDERS_FAIL = 'LIST_ORDERS_FAIL'
export const LIST_ORDERS_RESET = 'LIST_ORDERS_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'


export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST'
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS'
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL'
export const ORDER_UPDATE_RESET = 'ORDER_UPDATE_RESET'

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'


export const GET_ORDER_STATUS_ENUMS_REQUEST = 'GET_ORDER_STATUS_ENUMS_REQUEST'
export const GET_ORDER_STATUS_ENUMS_SUCCESS = 'GET_ORDER_STATUS_ENUMS_SUCCESS'
export const GET_ORDER_STATUS_ENUMS_FAIL = 'GET_ORDER_STATUS_ENUMS_FAIL'
export const GET_ORDER_STATUS_ENUMS_RESET = 'GET_ORDER_STATUS_ENUMS_RESET'
