export const SUBMIT_ORDER_REQUEST = "SUBMIT_ORDER_REQUEST";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const SUBMIT_ORDER_FAIL = "SUBMIT_ORDER_FAIL";
export const SUBMIT_ORDER_RESET = "SUBMIT_ORDER_RESET";


export const LIST_SUBMISSIONS_REQUEST = "LIST_SUBMISSIONS_REQUEST";
export const LIST_SUBMISSIONS_SUCCESS = "LIST_SUBMISSIONS_SUCCESS";
export const LIST_SUBMISSIONS_FAIL = "LIST_SUBMISSIONS_FAIL";
export const LIST_SUBMISSIONS_RESET = "LIST_SUBMISSIONS_RESET";

export const DELETE_SUBMIT_ORDER_REQUEST = "DELETE_SUBMIT_ORDER_REQUEST";
export const DELETE_SUBMIT_ORDER_SUCCESS = "DELETE_SUBMIT_ORDER_SUCCESS";
export const DELETE_SUBMIT_ORDER_FAIL = "DELETE_SUBMIT_ORDER_FAIL";
export const DELETE_SUBMIT_ORDER_RESET = "DELETE_SUBMIT_ORDER_RESET";