export const WRITER_CREATE_REQUEST = 'WRITER_CREATE_REQUEST'
export const WRITER_CREATE_SUCCESS = 'WRITER_CREATE_SUCCESS'
export const WRITER_CREATE_FAIL = 'WRITER_CREATE_FAIL'
export const WRITER_CREATE_RESET = 'WRITER_CREATE_RESET'


export const LIST_WRITER_REQUEST = 'LIST_WRITER_REQUEST'
export const LIST_WRITER_SUCCESS = 'LIST_WRITER_SUCCESS'
export const LIST_WRITER_FAIL = 'LIST_WRITER_FAIL'
export const LIST_WRITER_RESET = 'LIST_WRITER_RESET'

export const WRITER_DELETE_REQUEST = 'WRITER_DELETE_REQUEST'
export const WRITER_DELETE_SUCCESS = 'WRITER_DELETE_SUCCESS '
export const WRITER_DELETE_FAIL = 'WRITER_DELETE_FAIL'


export const LIST_STATUS_ENUMS_REQUEST = 'LIST_STATUS_ENUMS_REQUEST'
export const LIST_STATUS_ENUMS_SUCCESS = 'LIST_STATUS_ENUMS_SUCCESS'
export const LIST_STATUS_ENUMS_FAIL = 'LIST_STATUS_ENUMS_FAIL'
export const LIST_STATUS_ENUMS_RESET = 'LIST_STATUS_ENUMS_RESET'


export const LIST_GENDER_ENUMS_REQUEST = 'LIST_GENDER_ENUMS_REQUEST'
export const LIST_GENDER_ENUMS_SUCCESS = 'LIST_GENDER_ENUMS_SUCCESS'
export const LIST_GENDER_ENUMS_FAIL = 'LIST_GENDER_ENUMS_FAIL'
export const LIST_GENDER_ENUMS_RESET = 'LIST_GENDER_ENUMS_RESET'


export const LIST_TYPES_ENUMS_REQUEST = 'LIST_TYPES_ENUMS_REQUEST'
export const LIST_TYPES_ENUMS_SUCCESS = 'LIST_TYPES_ENUMS_SUCCESS'
export const LIST_TYPES_ENUMS_FAIL = 'LIST_TYPES_ENUMS_FAIL'
export const LIST_TYPES_ENUMS_RESET = 'LIST_TYPES_ENUMS_RESET'


export const UPDATE_WRITER_REQUEST = 'UPDATE_WRITER_REQUEST'
export const UPDATE_WRITER_SUCCESS = 'UPDATE_WRITER_SUCCESS'
export const UPDATE_WRITER_FAIL = 'UPDATE_WRITER_FAIL'
export const UPDATE_WRITER_RESET = 'UPDATE_WRITER_RESET'


export const WRITER_DETAILS_REQUEST = 'WRITER_DETAILS_REQUEST'
export const WRITER_DETAILS_SUCCESS = 'WRITER_DETAILS_SUCCESS'
export const WRITER_DETAILS_FAIL = 'WRITER_DETAILS_FAIL'


export const WRITER_DETAILS_USER_REQUEST = 'WRITER_DETAILS_USER_REQUEST'
export const WRITER_DETAILS_USER_SUCCESS = 'WRITER_DETAILS_USER_SUCCESS'
export const WRITER_DETAILS_USER_FAIL = 'WRITER_DETAILS_USER_FAIL'